# IMPORT

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from Dataset.MNIST.mnist import load_mnist

In [3]:
from Common.functions import *
from Common.gradient import *

In [4]:
import matplotlib.pyplot as plt

-----

# 간단한 신경망에서의 경사 하강법

In [5]:
class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2,3)

    def predict(self, x):
        return np.dot(x, self.W)

    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)

        return loss

In [6]:
net = simpleNet()
print(net.W)

[[ 1.82493671 -1.0907996   3.57325123]
 [-1.28518976 -0.40391509 -1.09899912]]


In [7]:
x = np.array([0.6, 0.9])
t = np.array([0, 0, 1])

In [8]:
p = net.predict(x)
print(p)

[-0.06170875 -1.01800334  1.15485153]


In [9]:
np.argmax(p)

2

In [10]:
t = np.array([0,0,1])
print(net.loss(x,t))

0.34366016046404324


In [11]:
f = lambda w: net.loss(x, t)

In [12]:
dW = numerical_gradient(f, net.W)

print(dW)

[[ 0.12605382  0.04844428 -0.1744981 ]
 [ 0.18908073  0.07266643 -0.26174715]]
